### ISSUE TITLE
メインページのヘッダーについて

### ISSUE THREAD

**Issue by MasuoK** [Kyutech-C3/OpenCampus#12]
**Is your feature request related to a problem? Please describe.**
メインページのヘッダーの実装をお願いします.
ブランチ名は "header" です.
OC当日とそれ以外の2つを作ってもらう必要があるので, 2つ別々でブランチを切るのもアリです）. 

### OC 当日
* C3の解説（短め）
* gmail リンク
* Twitter タイムラインの埋め込み
* youtubeLiveの埋め込み

### OC 以外
* C3の解説（長め）
* gmail リンク
* Twitter タイムラインの埋め込み

## 中間報告までの内容
理想的には 中間報告 までに二つ終わるのが理想ですが, 間に合わない場合は OC 当日ver だけでも完成してもらえるとありがたいです.

**Comment by peru-6358** [comment]
@MasuoK 
headerの枠作ったので、確認お願いします。
OC当日とそれ以外で分けるのは、YoutubeLiveの有無だと思うんだけど、
簡単にだけど、時間指定でその部分の閲覧が可能にするよう実装しようと思うから、1つ作るだけでも大丈夫な気はするんだけど、どうかな？

**Comment by MasuoK** [comment]
時間指定でheader変えられるのならそっちの方がサーバー的にも良いと思いますー

**Comment by peru-6358** [comment]
了解です！
たぶん、JSをhtmlファイル内に書き込む形で実装する予定。

**Comment by MasuoK** [comment]
ヘッダーのC3の紹介文のところに若干隙間みたいなの空いてるかも
もしかしたら自分のやつと干渉してるせいかもしれないけど, 念のため確認してもらって良い？
<img width="1438" alt="スクリーンショット 2020-06-21 3 59 22" src="https://user-images.githubusercontent.com/44055381/85209857-3bdbe100-b376-11ea-8fe9-e54bfe92a51f.png">

**Comment by peru-6358** [comment]
了解、あとで確認しておきます
