### ISSUE TITLE
データベースの定義について

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus#17]
どんなテーブルが必要か考えましょう．ゲームや動画のデータはデータベースに保持させるのは難しいので，それ以外のメタ情報（タイトルとか説明とか）をもたせましょう．例えばですが，テーブルとして
- works
- teams
- comments
みたいな感じでしょうか．
あとあとみんなに担当を割り振りたいと思うのですが，どうでしょうかー？

**Comment by Simo-C3** [comment]
テーブルが分かってないので今は何も言えないです。すいません。明日いろいろ調べて勉強します。

担当割り振りいいと思います。ただ、先輩にヘルプを求めまくるかもです...

**Comment by naga-naga** [comment]
担当割り振りOKです．

テーブルはそんな感じでいいと思います．カラムはこんな風になるのかな

- works(作品ID，タイトル，作者(作った班)，説明)
- teams(ID，班名)
- comments(ID，作品ID，コメント)

**Comment by Simo-C3** [comment]
あ！テーブルってこの前のやつですか
すいません忘れてました..

**Comment by rkun123** [comment]
```
works(作品ID，タイトル，作者(作った班)，説明)
teams(ID，班名)
comments(ID，作品ID，コメント)
games(ID, UnityroomのURL)
videos(ID, 動画のファイル名)
3dmodels(ID, sketchfabのID)
```
- 上記モデルを定義しておき，Viewを作っているときに変更が必要になったモデルについてはIssueで相談
- とりあえずフロントを無視して全機能を仮実装

**Comment by rkun123** [comment]
### Pages
- `/`:  `index.html`
- `/work/<Int:work_id>`: `detail.html`

### Templates
- `base.html`
すべてのテンプレートの継承元
@rkun123 
- `index.html`
トップページ
@sadaharu58 
- `detail.html`
@Simo-C3 
作品ページ
- `partial/unity.html`
Unityゲームの埋め込み用テンプレート
@catgolem 
- `partial/video.html`
動画埋め込み用テンプレート
@naga-naga 
- `partial/3dmodel.html`
3Dモデル埋め込み用テンプレート
- `partial/comment.html`
コメント表示/追加用テンプレート
@rkun123

**Comment by rkun123** [comment]
とりあえず[モデルの定義を実装しました．](https://github.com/Kyutech-C3/OpenCampus2020/commit/2474f65276d2b782ae5c3e391cf032e6f40d0184)
```
# レポジトリの場所(OpenCampus2020)までcd
$ git checkout server
$ git fetch
$ git rebase origin/server
$ cd server
$ python manage.py migrate
$ python manage.py createsuperuser
# ユーザー名とメルアドとパスワードを設定
$ python manage.py runserver
```
ブラウザにて`http://localhost:8000/admin`へアクセス
先程設定したユーザー情報でログイン
![](https://i.imgur.com/Zrpk8N7.png)
ここまでやっておいて下さーい！
わからなければコメントしてもらって．．．
