### ISSUE TITLE
中間報告スライドの作成

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus#18]
![](https://media.discordapp.net/attachments/711169298013618207/720566941382869019/6c2xfjC.png)
2. 制作物の概要
- 制作の動機，または目的
  - オープンキャンパスのみんなの出品物を手軽に見れて，（ゲームや3Dは触れて）コメントを残せるような特設Webサイトを作る
  - 展示物がWeb上で気軽に見れるようなサイトを作る
  - オンラインになって発表の場が少なくなってしまっているので外部に向けてC3の活動や成果物をアピールするためWeb上で手軽に見れるサイトは必要と考えた

- 使用している技術
  - サーバー
    - Python
    - Django
    - PostgreSQL
  - フロントエンド
    - HTML/CSS/JavaScript
    - Video.js
    - Unityroom
    - Bulma

- 制作物のアピールポイント
  - 作品がその場で触れられる(ゲーム: 遊べる，3Dモデル: 動かせる)
  - コメント機能で閲覧者からのフィードバックが得られる
  - モダンなUI
  - 作品の情報更新が容易

- 今後の展望
3. 期日までの制作計画
  フロントエンド
```
デザインコンペ：5/28（木）
HTMLによる雛形（ボタンの配置, アニメーションをしないページ遷移等）の作成：5/29（金）~ 6/7（日）
CSS, アニメーションの作成1：6/8（月）~ 6/13（土）
中間報告：6/14（日）
CSS, アニメーションの作成2：6/15（月）~ 6/18（木）
```
サーバー
```
6/11 データベース設計と割り振り
6/12 - 18 データベース実装/仮実装
6/30 - 7/4 完成したフロントエンドをサーバーに組み込んで本実装
```
4. 本番の展示会で考えている展示方式
**Web**

### 制作
Googleスライド

**Comment by Kinakonoko** [comment]
GoogleスライドのURLです
https://docs.google.com/presentation/d/1nl3TrOPNmKKzZDtqEkF559x_6fQUooI90wQxPqCwg_k/edit?usp=sharing

**Comment by Kinakonoko** [comment]
スライドの内容やレイアウトについての画像（？）を貼る…？の感じの内容を聞いたと思うのですが、そのファイルってどこにありますか？

**Comment by rkun123** [comment]
あー画像作ってたんですが，画像を貼る形にするとスライドのデザインと整合性が取れなくてキモくなるので私に編集権限をくれれば「使用技術」スライドだけ作っておきますね

**Comment by Kinakonoko** [comment]
権限の変更をしておきました！対応よろしくお願いします！！
