### ISSUE TITLE
embedding_unity

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus#4]
**Is your feature request related to a problem? Please describe.**
Unityは[標準でWeb書き出し機能がある](https://www.sejuku.net/blog/58732)んですが、これだと一枚のページとしてでてきます。
これだと独立したページになってしまってちょっとダサいので、サイトの一部に埋め込みたいです。

**Describe the solution you'd like**
とりあえず、HTMLのタグに埋め込むことができるような手法を考えてほしいです。
おそらく、Unityが吐き出したHTMLを読んで、実際のゲームの部分のHTMLタグを取り出してみる感じになるのでは？と思います。

**Describe alternatives you've considered**
または、[iframe](https://developer.mozilla.org/ja/docs/Web/HTML/Element/iframe)というWebページの中にWebページを埋め込む機能があるのですが、それだとUnityが吐き出したゲーム以外の部分（ロゴとか説明文とか）が入っちゃうのがいやなんですよねー

**Additional context**

**Comment by Kinakonoko** [comment]
サンプルゲームからゲーム部分だけ抜き出してそのHTMLファイルと関連ファイル類をここにアップするところまでやってみます。

**Comment by Kinakonoko** [comment]
[OC.zip](https://github.com/Kyutech-C3/OpenCampus2020/files/4671724/OC.zip)
おそらく書き出しはできたのですが、HTMLファイルのどこの部分を抜き出せばいいのか教えていただけたらありがたいです

**Comment by rkun123** [comment]
ブラウザで実際に動かしてみました？
Chromeでサイトを右クリックして「検証」を押すとDev toolsが出てきまして，そこからわかりやすい形でHTMLのコードとレンダリング結果が見れます．

**Comment by Kinakonoko** [comment]
edgeなら動くんですが、chromeだとこの画面が出て動かないのですが何か対処法ありますかね、、
![キャプチャ](https://user-images.githubusercontent.com/65017059/82872775-76687e80-9f6e-11ea-9422-18d4371060ae.PNG)

**Comment by I-My-Prog** [comment]
Chromeではセキュリティ上の観点からローカルのWebGL実行が禁止されているようです。
起動しているChromeをすべて終了し、コマンドラインから --allow-file-access-from-filesオプションを付けて起動することで解決する可能性があります。
参考：https://blog.56doc.net/Entry/809/
by.akata

**Comment by rkun123** [comment]
私はシンプルなHTTPサーバーを起動して動かしてます．
LinuxでPythonが入っていれば`python -m http.server 8000`だけで終わりなんですが，Windowsであれば[ここ](https://qiita.com/massie_g/items/2913066e596dae197539)とか見てもらえるといくつかソフトが有るのでできると思います．
ドキュメントルートを書き出したフォルダーにして`http://localhost:ポート番号/index.html`にChromeからアクセスすればOKです．

**Comment by Kinakonoko** [comment]
オプションをつけて起動することでchromeでの動作はできるようになりました。
一応unityのロゴとゲーム名部分を消してゲーム本体の画面だけにはしたのですがこの感じでいいですか？
[OC.zip](https://github.com/Kyutech-C3/OpenCampus2020/files/4681070/OC.zip)

**Comment by rkun123** [comment]
いい感じですね！
ブラウザ領域全体に表示できれば嬉しいので，そこら辺調べてみていただきたいです！

**Comment by Kinakonoko** [comment]
一応できました！webglに書き出して、buildの中のファイルの.jsonのファイル名をwebglに変えてbuildファイル内をすべてHTMLのあるファイル内に入れて、unityroomにアップロードしてやるとできるようになりました！

ただ、この手法だと、いくつかのファイルをunityroomなどのサイトから拾って表示させている感じなのですが、これでOKですか？
[OC sample1.zip](https://github.com/Kyutech-C3/OpenCampus2020/files/4762140/OC.sample1.zip)
