### ISSUE TITLE
Djangoのチュートリアル

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus#9]
今回バリバリDjangoを使っていくのですが，とりあえず最初は[ここ](https://docs.djangoproject.com/ja/3.0/intro/tutorial01/)の**「その1」から「その5」**までをやってみていただきたいと思います．
このチュートリアルに沿って学習すればDjangoの大体の部分は理解できると思います．
質問があればIssueコメントでもDiscordでもMastodonでも良いので投げてください！

**Comment by rkun123** [comment]
ちなみに今日（2020-06-06）Python勉強会やろうと思うのでよろしくおねがいします！！

**Comment by Simo-C3** [comment]
楽しかったです！
めっちゃ理解できました！！！
チュートリアルは出来たんで内容理解頑張ります。いつぐらいから本格スタートしますか？

**Comment by rkun123** [comment]
よかったです！
そろそろみなチュートリアルが終わってきた感じなので，プロジェクトを作成して作っていきましょう！
